apiVersion: v1
kind: Service
metadata:
  name: feedback-node-port-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31600
  selector: 
    component: nginx